---
# tasks file for roles/win_ad_install
- name: Install and Configure AD On Windows System
  debug:
    msg: "Install and Configure AD On Windows System test"

- name: Install AD-Domain-Services feature
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present

- name:  Configure AD-Domain-Services
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: win_do_reboot

- name: Reboot Windows System
  win_reboot:
  when: win_do_reboot.reboot_required
  async: 0
  poll: 0
  ignore_errors: true
