---
# tasks file for appdbs
- name: deploy postgres
#####  hosts: apps
  debug:
    msg: "start deploy postgres"

#####  - name: install progress
- name: install postgresql-server
  yum:
    name: postgresql-server
    state: installed
#####    command: "yum install -y postgresql-server"

#- name: install postgres
#  yum:
#    name: postgresql-server
#    state: latest
- name: enable apache at boot
  service:
    name: postgresql
    enabled: yes
- name: tell user to finish setting up postgres
  debug:
    msg: "Either uncomment the postgres setup or manually login and initialize"

# only run the next 2 tasks once!
- name: check postgresql is exist
  stat:
    path: /var/lib/pgsql/data/pg_hba.conf
  register: pgdata_stat

- name: initilize postgres
  command: postgresql-setup initdb
  when: not pgdata_stat.stat.exists
#####    command: systemctl preset postgresql.service
#####    command: postgresql-setup initdb
  run_once: true
#    ignore_errors: true
- name: initilize postgres some more
  command: chkconfig postgresql on
  run_once: true
  when: not pgdata_stat.stat.exists
#  - name: initilize postgres
#    command: postgresql-setup initdb
#  - name: initilize postgres some more
#    command: chkconfig postgresql on
- name: start postgres
  service:
    name: postgresql.service
    state: started
